[package]
name = "bellpepper_r1cs"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["SunJc"]

[dependencies]
ff = "0.13.0"
byteorder = "1"
num-bigint = { version = "0.4", default-features = false }
bellpepper-core = "0.4.0"

[dev-dependencies]
zkutil = "0.5.0"
halo2curves = "0.8.0"

